name: Lexicon Updater

on:
  schedule:
  - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update-lexicons:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make pull_atproto.sh executable
        run: |
          chmod +x ./.scripts/pull_atproto.sh

      - name: Pull lexicons from atproto repo
        run: ./.scripts/pull_atproto.sh

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.Lexicon_Updater }}
        run: |
            git config --local user.name "Lexicon Updater"
            git config --local user.email "bray.cade@gmail.com"
            git add .
            git commit -m "Update lexicons"
            git push